# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Conditional Publish to npm

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      version_changed: ${{ steps.check.outputs.changed }}
      new_version: ${{ steps.check.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Check if version has been updated
        id: check
        run: |
          git diff HEAD^ HEAD -- package.json | grep '"version"' || echo "No version change"
          if git diff HEAD^ HEAD -- package.json | grep '"version"'; then
            echo "changed=true" >> $GITHUB_OUTPUT
            new_version=$(git diff HEAD^ HEAD -- package.json | grep '"version"' | cut -d'"' -f4)
            echo "version=$new_version" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

  publish-npm:
    needs: check-version
    if: needs.check-version.outputs.version_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v${{ needs.check-version.outputs.new_version }} \
            --title "Release ${{ needs.check-version.outputs.new_version }}" \
            --notes "Version ${{ needs.check-version.outputs.new_version }} has been published to npm."
